<script>
	import Fa from 'svelte-fa';
	import { faExclamationCircle, faL, faSpinner } from '@fortawesome/free-solid-svg-icons';
	import { slide } from 'svelte/transition';
	import { enhance } from '$app/forms';
	import PasswordModule from '$components/auth/passwordModule.svelte';
	// let email;

	let loading = $state(false);
	let completed = $state(false);
	let Invalid = $state();
	let errMessage = $state();

	const handleSubmit = ({ cancel }) => {
		if (Invalid) {
			cancel();
			return;
		}
		loading = true;
		return async ({ update, result }) => {
			loading = false;
			if (result.type == 'success') {
				completed = true;
			} else {
				errMessage = result.data.message;
				setTimeout(() => {
					errMessage = '';
				}, 3000);
			}
			await update();
		};
	};
</script>

<svelte:head>
	<title>Forgot password - devCanvas</title>
</svelte:head>

<div class="flex h-screen items-center justify-center bg-white text-primary">
	<div
		class="hidden h-full flex-col items-center justify-center bg-secondary-dark md:flex md:flex-1"
	>
		<img src="/logo.svg" class=" h-24 rounded-3xl" alt="DevCanvas Logo" />
		<a href="/" class="text-center text-3xl text-white md:text-5xl">
			Dev<span class="text-sky-500">Canvas</span>
		</a>
	</div>
	<form
		transition:slide
		action="?/reset"
		method="post"
		use:enhance={handleSubmit}
		class="mt-2 flex w-full max-w-xl flex-col gap-4 rounded-lg p-6 md:p-6 md:px-16"
	>
		<!-- <img src="/logo.svg" class=" h-24 rounded-3xl" alt="DevCanvas Logo" /> -->

		<h2 class="mb-12 text-center text-3xl md:text-3xl">Reset Password</h2>

		<div class="flex flex-col gap-3">
			<PasswordModule {loading} submitText={'Update password'} bind:message={Invalid} />
		</div>

		{#if completed}
			<div
				in:slide={{ axis: 'y' }}
				out:slide
				class="mt-2 flex h-6 w-fit items-center justify-start gap-2 rounded-md bg-green-400 p-2 py-4 text-sm text-black md:text-base"
			>
				<span> <Fa icon={faExclamationCircle} /></span><span transition:slide>Password updated</span
				>
			</div>

			<div>
				<a href="/dashboard">Go to dashboard</a>
			</div>
		{/if}
	</form>
	{#if errMessage}
		<p transition:slide class="rounded-md bg-error p-2">{errMessage}</p>
	{/if}
</div>

<style>
	.wobble-hor-top {
		-webkit-animation: wobble-hor-top 0.8s 3000ms infinite both;
		animation: wobble-hor-top 0.8s 3000ms infinite both;
	}
	/* ----------------------------------------------
 * Generated by Animista on 2023-9-14 23:15:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation wobble-hor-top
 * ----------------------------------------
 */
	@-webkit-keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}

	@keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}
</style>
