<script>
	import Fa from 'svelte-fa';
	import { faExclamationCircle, faL, faSpinner } from '@fortawesome/free-solid-svg-icons';
	import { slide } from 'svelte/transition';
	import { enhance } from '$app/forms';
	import PasswordModule from '$components/auth/passwordModule.svelte';
	let email;
	let loading = false;
	let completed = false;
	let Invalid;
	let errMessage;

	const handleSubmit = ({ cancel }) => {
		if (Invalid) {
			cancel();
			return;
		}
		loading = true;
		return async ({ update, result }) => {
			loading = false;
			if (result.type == 'success') {
				completed = true;
			} else {
				errMessage = result.data.message;
				setTimeout(() => {
					errMessage = '';
				}, 2000);
			}
			// await update();
		};
	};
</script>

<svelte:head>
	<title>Forgot password - devCanvas</title>
</svelte:head>

<div class="h-screen flex flex-col items-center justify-center bg-white text-primary">
	<!-- <InnerNav /> -->
	<form
		transition:slide
		action="?/reset"
		method="post"
		use:enhance={handleSubmit}
		class="flex flex-col gap-4 w-full max-w-xl p-6 md:p-6 md:px-16 rounded-lg mt-2"
	>
		<img src="/logo.svg" class=" h-24 rounded-3xl" alt="DevCanvas Logo" />

		<h2 class="text-3xl md:text-5xl text-center">Dev<span class="text-sky-500">Canvas</span></h2>

		<div class="flex flex-col gap-3">
			<PasswordModule {loading} submitText={'Update password'} bind:message={Invalid} />
		</div>

		{#if completed}
			<div
				in:slide={{ axis: 'y' }}
				out:slide
				class="bg-green-400 w-fit py-4 text-black h-6 mt-2 rounded-md p-2 gap-2 text-sm md:text-base flex items-center justify-start"
			>
				<span> <Fa icon={faExclamationCircle} /></span><span transition:slide>Password updated</span
				>
			</div>
		{/if}
	</form>
	{#if errMessage}
		<p transition:slide class="bg-error p-2 w-full rounded-md">{errMessage}</p>

		<div>
			<a href="/dashboard">Go to dashboard</a>
		</div>
	{/if}
</div>

<style>
	.wobble-hor-top {
		-webkit-animation: wobble-hor-top 0.8s 3000ms infinite both;
		animation: wobble-hor-top 0.8s 3000ms infinite both;
	}
	/* ----------------------------------------------
 * Generated by Animista on 2023-9-14 23:15:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation wobble-hor-top
 * ----------------------------------------
 */
	@-webkit-keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}

	@keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}
</style>
