<script>
	import Fa from 'svelte-fa';
	import { faExclamationCircle, faSpinner } from '@fortawesome/free-solid-svg-icons';
	import { faGithub, faGoogle } from '@fortawesome/free-brands-svg-icons';
	import { slide } from 'svelte/transition';
	import { enhance } from '$app/forms';
	import { page } from '$app/stores';
	import PasswordInput from '$components/auth/passwordInput.svelte';

	import {  deserialize } from '$app/forms';

	let email;
	let password;
	let loading = false;
	let completed = false;
	let usePassword = false;
	let errMessage;

	// export let form;

	const handleSubmit = () => {
		loading = true;

		return async ({ update, result }) => {
			loading = false;
			completed = true;
			// console.log(result);
			if (result.status == 400) {
				errMessage = result.data.message;
				setTimeout(() => {
					errMessage = '';
				}, 3000);
			}
			await update();
		};
	};
	function openAuthPopup(url, name = "authPopup", width = 500, height = 600) {
  const left = (screen.width / 2) - (width / 2);
  const top = (screen.height / 2) - (height / 2);

  const popup = window.open(
    url,
    name,
    `width=${width},height=${height},top=${top},left=${left},resizable,scrollbars=yes,status=1`
  );

  if (!popup) {
    alert("Please allow popups for this site.");
    return;
  }


  popup.focus();

  
  return popup;
}

	const handleOauth = async (path)=>{

		const response = await fetch(path, {method:'post', body: new FormData()});
		let dat = deserialize(await response.text())
		openAuthPopup(dat.data.url)
	}
</script>

<svelte:head>
	<title>Sign In - DevCanvas</title>

	<meta name="description" content={'Sign in to DevCanvas - Prototype with EASE!'} />

	<!-- Facebook Meta Tags -->
	<meta property="og:url" content={'Sign in to DevCanvas - Prototype with EASE!'} />
	<meta property="og:type" content="website" />
	<meta property="og:description" content={'Sign in to DevCanvas - Prototype with EASE!'} />
	<meta property="og:image" content={'Sign in to DevCanvas - Prototype with EASE!'} />

	<!-- Twitter Meta Tags -->
	<meta name="twitter:card" content="summary_large_image" />
	<meta property="twitter:domain" content="devcanvas.art" />
	<meta property="twitter:url" content={'Sign in to DevCanvas - Prototype with EASE!'} />
	<meta name="twitter:description" content={'Sign in to DevCanvas - Prototype with EASE!'} />
	<meta name="twitter:image" content={'Sign in to DevCanvas - Prototype with EASE!'} />
	<meta
		name="keywords"
		content="css, html, css art, css animation, code snippet, javascript animations, animation with html/css,"
	/>
</svelte:head>

<div class="flex h-screen items-center justify-center bg-white text-primary">
	<!-- <InnerNav /> -->
	<div
		class="hidden h-full flex-col items-center justify-center bg-secondary-dark md:flex md:flex-1"
	>
		<img src="/logo.svg" class=" h-24 rounded-3xl" alt="DevCanvas Logo" />
		<a href="/" class="text-center text-3xl text-white md:text-5xl">
			Dev<span class="text-sky-500">Canvas</span>
		</a>
	</div>
	<div class="max-w-xl flex-1 space-y-3 p-6 md:p-6 md:px-16">
		

		<div >
			

			<button
				class="my-3 flex w-full items-center justify-center gap-2 rounded border p-2 hover:bg-black/20"
				on:click={()=>handleOauth('?/github')}
			>
				Continue with Github <Fa icon={faGithub} />
			</button>
		</div>
		<div class="my-4 flex items-center gap-2">
			<div class="flex-grow border-t border-gray-300"></div>
			<span class="text-sm text-gray-500">OR</span>
			<div class="flex-grow border-t border-gray-300"></div>
		</div>
		<div>
	

			<button
				class="my-3 flex w-full items-center justify-center gap-2 rounded border p-2 hover:bg-black/20"
				on:click={()=>handleOauth('?/google')}
			>
				Continue with Google <Fa icon={faGoogle} />
			</button>

			<!-- <div class="my-4 flex items-center gap-2">
				<div class="flex-grow border-t border-gray-300"></div>
				<span class="text-sm text-gray-500">OR</span>
				<div class="flex-grow border-t border-gray-300"></div>
			</div> -->

		</div>

		<!-- <p class="text-sm">Don't have an account? <a href="/signup">Sign Up</a></p> -->
		<!-- <a class="text-sm" href="recovery/forgot">Forgot password?</a> -->

		{#if errMessage}
			<p transition:slide={{ duration: 200 }} class="w-full rounded-md bg-error p-2">
				{errMessage}
			</p>
		{/if}
	</div>
</div>

<style>
	a {
		@apply text-sky-600;
	}
	.wobble-hor-top {
		-webkit-animation: wobble-hor-top 0.8s 3000ms infinite both;
		animation: wobble-hor-top 0.8s 3000ms infinite both;
	}
	/* ----------------------------------------------
 * Generated by Animista on 2023-9-14 23:15:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation wobble-hor-top
 * ----------------------------------------
 */
	@-webkit-keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}

	@keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}
</style>
