<script>
	import Fa from 'svelte-fa';
	import { faExclamationCircle, faSpinner } from '@fortawesome/free-solid-svg-icons';
	import { slide } from 'svelte/transition';
	import { enhance } from '$app/forms';
	let email;
	let loading = false;
	let completed = false;
	let errMessage;

	const handleSubmit = () => {
		loading = true;

		return async ({ update, result }) => {
			loading = false;
			if (result.status == 200) {
				completed = true;
			} else {
				errMessage = result.data.message;
			}
			// completed = true;
			await update();
		};
	};
</script>

<svelte:head>
	<title>Forgot password - devCanvas</title>
</svelte:head>

<div class="flex h-screen items-center justify-center bg-white text-primary">
	<!-- <InnerNav /> -->

	<div
		class="hidden h-full flex-col items-center justify-center bg-secondary-dark md:flex md:flex-1"
	>
		<img src="/logo.svg" class=" h-24 rounded-3xl" alt="DevCanvas Logo" />
		<a href="/" class="text-center text-3xl text-white md:text-5xl">
			Dev<span class="text-sky-500">Canvas</span>
		</a>
	</div>
	<form
		transition:slide
		action="?/forgot"
		method="post"
		use:enhance={handleSubmit}
		class="mt-2 flex w-full max-w-xl flex-col gap-4 rounded-lg p-6 md:p-6 md:px-16"
	>
		<h2 class="mb-12 text-center text-3xl md:text-3xl">Forgot Password</h2>
		<div class="flex flex-col gap-3">
			<div transition:slide class="flex flex-col gap-2">
				<label for="email" class="text-sm">Email</label>
				<input
					name="email"
					type="email"
					id="email"
					bind:value={email}
					required
					class="rounded-lg border border-sky-200 px-3 py-2 outline outline-2 outline-sky-200 focus:outline-4 focus:outline-sky-300"
				/>
			</div>

			<button
				aria-busy={loading}
				type="submit"
				class="flex items-center justify-center gap-2 rounded-md bg-sky-300 p-2 text-black"
				>Send Reset Email

				{#if loading}
					<Fa icon={faSpinner} class="animate-spin" />
				{/if}
			</button>
		</div>

		{#if completed}
			<div
				in:slide={{ axis: 'y' }}
				out:slide
				class="mt-2 flex h-6 w-fit items-center justify-start gap-2 rounded-md bg-green-400 p-2 py-4 text-sm text-black md:text-base"
			>
				<span> <Fa icon={faExclamationCircle} /></span><span transition:slide>Email sent</span>
			</div>
		{/if}
	</form>
</div>

<style>
	.wobble-hor-top {
		-webkit-animation: wobble-hor-top 0.8s 3000ms infinite both;
		animation: wobble-hor-top 0.8s 3000ms infinite both;
	}
	/* ----------------------------------------------
 * Generated by Animista on 2023-9-14 23:15:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation wobble-hor-top
 * ----------------------------------------
 */
	@-webkit-keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}

	@keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}
</style>
