<script>
	import { current_data, isOwner } from '$lib/index.js';
	import { saveData } from '$lib/feEditor/store.js';
	import { faPen } from '@fortawesome/free-solid-svg-icons';
	import Fa from 'svelte-fa';
	import { getProfile } from '$lib/utils.js';

	import { page } from '$app/stores';
	import { onMount } from 'svelte';
	import ShowLoginOrforkBanner from './showLoginOrforkBanner.svelte';

	let supabase = $page.data.supabase;
	let session = $page.data.session;

	let typingTimer; // Timer to track typing
	const delay = 1000; // Adjust the delay as needed (in milliseconds)

	// Function to handle text input
	function handleInput(event) {
		if (!$isOwner) return;
		let text = event.target.innerText;
		console.log(text);
		current_data.update((cur) => {
			// console.log(cur);
			return { ...cur, description: text };
		});
		clearTimeout(typingTimer); // Clear the previous timer

		typingTimer = setTimeout(function () {
			// This function will run after the delay (user has stopped typing)
			saveToServer();
		}, delay);
	}

	// Function to save text to the server (simulated)
	function saveToServer() {
		// Send a request to the server with the text data
		// You can use AJAX, Fetch API, or any other method to send data to the server
		console.log('saving data');
		saveData($current_data, 'description');
	}

	function handleKeyDown(event) {
		if (event.key === 'Enter' || event.keyCode === 13) {
			event.preventDefault();
		}
	}

	$: profile = [];

	onMount(async () => {
		console.log('mounted');
		if ($current_data.user_id == session?.user?.id) return;
		try {
			let profile_data = await getProfile($current_data.user_id, supabase);
			console.log(profile_data);
			if (profile_data.length > 0) {
				profile = profile_data;
			}
		} catch (error) {
			throw error;
		}
	});
</script>

<div class="flex flex-col w-full">
	{#if $isOwner}
		<div class="flex gap-2 items-center" style="margin-bottom: -7px;">
			<p
				contenteditable=""
				on:keydown={handleKeyDown}
				on:input={handleInput}
				placeholder="Untitled Project"
				class="max-w-[100px] md:max-w-full w-fit text-sm md:text-xl capitalize text-white bg-inherit outline-none whitespace-nowrap overflow-hidden text-ellipsis"
			>
				{$current_data.description}
			</p>
			<span class="text-white text-[11px] md:text-base jello-diagonal-2 cursor-pointer">
				<Fa icon={faPen} />
			</span>
		</div>
	{:else}
		<p
			style="margin-bottom: -7px;"
			class="max-w-[100px] md:max-w-full w-fit text-sm md:text-xl capitalize text-white bg-inherit outline-none whitespace-nowrap overflow-hidden text-ellipsis"
		>
			{$current_data.description}
		</p>
	{/if}

	{#if profile.length > 0}
		<div class="flex text-[9px] md:text-sm gap-2">
			<p
				class="text-sky-400 dark:text-sky-300 outline-none focus:outline-sky-300 p-1 focus:dark:outline-sky-400 rounded-lg"
				spellcheck="false"
			>
				<span>by</span>
				<a href={`/${profile[0].username}`}>@{profile[0].username}</a>
			</p>
			<ShowLoginOrforkBanner />
		</div>
	{:else}
		<p
			class="text-sky-400 dark:text-sky-300 outline-none focus:outline-sky-300 p-1 focus:dark:outline-sky-400 rounded-lg text-sm"
			spellcheck="false"
		>
			<a href="/html-playground">&larr;backHome</a>
		</p>
	{/if}
</div>

<style>
	.jello-diagonal-2:hover {
		-webkit-animation: jello-diagonal-2 0.8s infinite alternate-reverse both;
		animation: jello-diagonal-2 0.8s infinite alternate-reverse both;
	}

	/* ----------------------------------------------
 * Generated by Animista on 2023-9-22 9:1:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation jello-diagonal-2
 * ----------------------------------------
 */
	@-webkit-keyframes jello-diagonal-2 {
		0% {
			-webkit-transform: skew(0deg 0deg);
			transform: skew(0deg 0deg);
		}
		30% {
			-webkit-transform: skew(-25deg -25deg);
			transform: skew(-25deg -25deg);
		}
		40% {
			-webkit-transform: skew(15deg, 15deg);
			transform: skew(15deg, 15deg);
		}
		50% {
			-webkit-transform: skew(-15deg, -15deg);
			transform: skew(-15deg, -15deg);
		}
		65% {
			-webkit-transform: skew(5deg, 5deg);
			transform: skew(5deg, 5deg);
		}
		75% {
			-webkit-transform: skew(-5deg, -5deg);
			transform: skew(-5deg, -5deg);
		}
		100% {
			-webkit-transform: skew(0deg 0deg);
			transform: skew(0deg 0deg);
		}
	}
	@keyframes jello-diagonal-2 {
		0% {
			-webkit-transform: skew(0deg 0deg);
			transform: skew(0deg 0deg);
		}
		30% {
			-webkit-transform: skew(-25deg -25deg);
			transform: skew(-25deg -25deg);
		}
		40% {
			-webkit-transform: skew(15deg, 15deg);
			transform: skew(15deg, 15deg);
		}
		50% {
			-webkit-transform: skew(-15deg, -15deg);
			transform: skew(-15deg, -15deg);
		}
		65% {
			-webkit-transform: skew(5deg, 5deg);
			transform: skew(5deg, 5deg);
		}
		75% {
			-webkit-transform: skew(-5deg, -5deg);
			transform: skew(-5deg, -5deg);
		}
		100% {
			-webkit-transform: skew(0deg 0deg);
			transform: skew(0deg 0deg);
		}
	}
</style>
