<script>
	import { current_data, isOwner } from '$lib/index.js';
	import { showLoginToSave } from '$lib/feEditor/store.js';

	import { saveData } from '$lib/feEditor/store.js';
	import { faPen } from '@fortawesome/free-solid-svg-icons';
	import Fa from 'svelte-fa';
	import { getProfile } from '$lib/utils.js';

	import { page } from '$app/stores';
	import { onDestroy, onMount } from 'svelte';
	import ShowLoginOrforkBanner from './showLoginOrforkBanner.svelte';
	import CanvasVisibility from './canvasVisibility.svelte';

	let supabase = $page.data.supabase;
	let session = $page.data.session;
	let typingTimer;
	const typingDelay = 1000;
	let description = $current_data.description;
	let title = null;

	try {
		title = description.split('Fork:')[1].trim();
	} catch (err) {
		// Handle the case where 'Fork:' is not present
	}

	function handleInput(event) {
		if (!$isOwner) return;
		let newDescription = event.target.innerText;
		if (title) {
			newDescription = `Fork: ${newDescription}`;
		}

		current_data.update((cur) => ({ ...cur, description: newDescription }));
		clearTimeout(typingTimer);

		typingTimer = setTimeout(() => {
			saveToServer();
		}, typingDelay);
	}

	function saveToServer() {
		saveData($current_data, 'description');
	}

	function handleKeyDown(event) {
		if (event.key === 'Enter' || event.keyCode === 13) {
			event.preventDefault();
		}
	}

	let profile = $current_data?.profiles?.username;
	// console.log($current_data)
	// onMount(async () => {
	// 	if ($current_data.user_id === session?.user?.id) return;
	// 	try {
	// 		const profileData = await getProfile($current_data.user_id, supabase);
	// 		if (profileData.length > 0) {
	// 			profile = profileData;
	// 		}
	// 	} catch (error) {
	// 		console.error(error);
	// 	}
	// });

	onDestroy(() => {
		// showForkToSave.set(false);
		showLoginToSave.set(false);
	});
</script>

<div class="flex w-full flex-col">
	{#if $isOwner}
		<div class="mb-[-7px] flex items-center gap-2">
			{#if title}
				<div class="flex w-fit max-w-[180px] items-center gap-1 md:max-w-[400px] xl:max-w-[600px]">
					<p class="rounded bg-sky-400 p-[1.3px] text-sm text-black md:text-xl">Fork</p>
					<div
						class="min-w-[50px] max-w-[160px] truncate bg-inherit text-sm font-semibold capitalize text-white focus:outline-1 focus:outline-sky-200 md:text-xl"
					>
						<h1
							contenteditable
							on:keydown={handleKeyDown}
							on:input={handleInput}
							placeholder="Untitled Project"
							spellcheck="false"
							class="truncate"
						>
							{title}
						</h1>
					</div>
				</div>
			{:else}
				<h1
					contenteditable
					on:keydown={handleKeyDown}
					on:input={handleInput}
					placeholder="Untitled Project"
					spellcheck="false"
					class="w-fit min-w-[50px] max-w-[180px] truncate bg-inherit text-sm font-semibold capitalize text-white focus:outline-1 focus:outline-sky-200 md:max-w-[400px] md:text-xl xl:max-w-[600px]"
				>
					{$current_data.description}
				</h1>
			{/if}
			<span class="jello-diagonal-2 cursor-pointer text-[11px] text-white md:text-base">
				<Fa icon={faPen} />
			</span>

			<CanvasVisibility canvas_id={$current_data.id} publicLy={$current_data.public} />
		</div>
	{:else if title}
		<div class="flex w-fit max-w-[180px] items-center gap-1 md:max-w-[400px] xl:max-w-[600px]">
			<p class="flex items-baseline rounded bg-sky-400 p-[1.3px] text-sm text-black md:text-xl">
				Fork
			</p>
			<div
				class="flex w-fit max-w-[160px] items-center gap-2 bg-inherit text-sm font-semibold capitalize text-white outline-none md:max-w-[400px] md:text-xl xl:max-w-[600px]"
			>
				<h1 class="truncate">
					{title}
				</h1>
			</div>
		</div>
	{:else}
		<div
			style="margin-bottom: -7px;"
			class="flex w-fit max-w-[180px] items-center gap-2 bg-inherit text-sm font-semibold capitalize text-white outline-none md:max-w-[400px] md:text-xl xl:max-w-[600px]"
		>
			<h1 class="truncate">
				{$current_data.description}
			</h1>
		</div>
	{/if}

	{#if profile}
		<div class="flex gap-1 text-[.8rem] md:text-sm">
			<p
				class="rounded-lg p-1 text-sky-400 outline-none focus:outline-sky-300 dark:text-sky-300 focus:dark:outline-sky-400"
				spellcheck="false"
			>
				<span>by</span>
				<a class="font-semibold" href={`/${profile}`}>@{profile}</a>
			</p>
			<!-- <ShowLoginOrforkBanner /> -->
		</div>
	{:else}
		<p
			class="rounded-lg p-1 text-sm text-sky-400 outline-none focus:outline-sky-300 dark:text-sky-300 focus:dark:outline-sky-400"
			spellcheck="false"
		>
			<a class="text-[.8rem] md:text-sm" href="/play">&larr;backHome</a>
		</p>
	{/if}
</div>

<style>
	.jello-diagonal-2:hover {
		-webkit-animation: jello-diagonal-2 0.8s infinite alternate-reverse both;
		animation: jello-diagonal-2 0.8s infinite alternate-reverse both;
	}

	/* ----------------------------------------------
 * Generated by Animista on 2023-9-22 9:1:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation jello-diagonal-2
 * ----------------------------------------
 */
	@-webkit-keyframes jello-diagonal-2 {
		0% {
			-webkit-transform: skew(0deg 0deg);
			transform: skew(0deg 0deg);
		}
		30% {
			-webkit-transform: skew(-25deg -25deg);
			transform: skew(-25deg -25deg);
		}
		40% {
			-webkit-transform: skew(15deg, 15deg);
			transform: skew(15deg, 15deg);
		}
		50% {
			-webkit-transform: skew(-15deg, -15deg);
			transform: skew(-15deg, -15deg);
		}
		65% {
			-webkit-transform: skew(5deg, 5deg);
			transform: skew(5deg, 5deg);
		}
		75% {
			-webkit-transform: skew(-5deg, -5deg);
			transform: skew(-5deg, -5deg);
		}
		100% {
			-webkit-transform: skew(0deg 0deg);
			transform: skew(0deg 0deg);
		}
	}
	@keyframes jello-diagonal-2 {
		0% {
			-webkit-transform: skew(0deg 0deg);
			transform: skew(0deg 0deg);
		}
		30% {
			-webkit-transform: skew(-25deg -25deg);
			transform: skew(-25deg -25deg);
		}
		40% {
			-webkit-transform: skew(15deg, 15deg);
			transform: skew(15deg, 15deg);
		}
		50% {
			-webkit-transform: skew(-15deg, -15deg);
			transform: skew(-15deg, -15deg);
		}
		65% {
			-webkit-transform: skew(5deg, 5deg);
			transform: skew(5deg, 5deg);
		}
		75% {
			-webkit-transform: skew(-5deg, -5deg);
			transform: skew(-5deg, -5deg);
		}
		100% {
			-webkit-transform: skew(0deg 0deg);
			transform: skew(0deg 0deg);
		}
	}
</style>
