<script>
	import {
		faCodeMerge,
		faExclamationTriangle,
		faRightToBracket
	} from '@fortawesome/free-solid-svg-icons';
	import Fa from 'svelte-fa';
	import { page } from '$app/stores';
	import { handleRedirectURL } from '$lib/utils.js';

	import { showLoginToSave, showForkTosave } from '$lib/feEditor/store.js';

	let signinURL = handleRedirectURL($page.url);
</script>

{#if $showLoginToSave}
	<div class="flex items-center justify-center gap-2 text-inherit">
		<span class="text-error wobble-hor-top"><Fa icon={faExclamationTriangle} /></span>
		<span class="text-light"
			><a href={signinURL} class="underline text-sky-300"> Login</a> to save progress</span
		>
	</div>
{:else if $showForkTosave}
	<div class="flex items-center justify-center gap-1 text-inherit">
		<span class="text-green-500 wobble-hor-top"><Fa icon={faCodeMerge} /></span>
		<span class="text-light"><a href="#" class=" text-green-500"> Fork</a> to save progress</span>
	</div>
{/if}

<style>
	.wobble-hor-top {
		-webkit-animation: wobble-hor-top 0.8s 4s infinite both;
		animation: wobble-hor-top 0.8s 4s infinite both;
	}
	/* ----------------------------------------------
 * Generated by Animista on 2023-9-14 23:15:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation wobble-hor-top
 * ----------------------------------------
 */
	@-webkit-keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}

	@keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}
</style>
