<script>
	import Fa from 'svelte-fa';
	import { faExclamationCircle, faSpinner } from '@fortawesome/free-solid-svg-icons';
	import { slide } from 'svelte/transition';
	import { enhance } from '$app/forms';
	let email;
	let loading = false;
	let completed = false;
	let errMessage;

	const handleSubmit = () => {
		loading = true;

		return async ({ update, result }) => {
			loading = false;
			if (result.status == 200) {
				completed = true;
			} else {
				errMessage = result.data.message;
			}
			// completed = true;
			await update();
		};
	};
</script>

<svelte:head>
	<title>Forgot password - devCanvas</title>
</svelte:head>

<div class="h-screen flex flex-col items-center justify-center bg-white text-primary">
	<!-- <InnerNav /> -->
	<form
		transition:slide
		action="?/forgot"
		method="post"
		use:enhance={handleSubmit}
		class="flex flex-col gap-4 w-full max-w-xl p-6 md:p-6 md:px-16 rounded-lg mt-2"
	>
		<img src="/logo.svg" class=" h-24 rounded-3xl" alt="DevCanvas Logo" />

		<h2 class="text-3xl md:text-5xl text-center">Dev<span class="text-sky-500">Canvas</span></h2>
		<div class="flex flex-col gap-3">
			<div transition:slide class="flex flex-col gap-2">
				<label for="email" class="text-sm">Email</label>
				<input
					name="email"
					type="email"
					id="email"
					bind:value={email}
					required
					class="border border-sky-200 p-1 rounded outline-none focus:outline focus:outline-sky-300"
				/>
			</div>

			<button
				aria-busy={loading}
				type="submit"
				class="p-2 rounded-md flex items-center justify-center gap-2 bg-[#0973a5] text-white"
				>Send Reset Email

				{#if loading}
					<Fa icon={faSpinner} class="animate-spin" />
				{/if}
			</button>
		</div>

		{#if completed}
			<div
				in:slide={{ axis: 'y' }}
				out:slide
				class="bg-green-400 w-fit py-4 text-black h-6 mt-2 rounded-md p-2 gap-2 text-sm md:text-base flex items-center justify-start"
			>
				<span> <Fa icon={faExclamationCircle} /></span><span transition:slide>Email sent</span>
			</div>
		{/if}
	</form>
</div>

<style>
	.wobble-hor-top {
		-webkit-animation: wobble-hor-top 0.8s 3000ms infinite both;
		animation: wobble-hor-top 0.8s 3000ms infinite both;
	}
	/* ----------------------------------------------
 * Generated by Animista on 2023-9-14 23:15:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation wobble-hor-top
 * ----------------------------------------
 */
	@-webkit-keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}

	@keyframes wobble-hor-top {
		0%,
		100% {
			-webkit-transform: translateX(0%);
			transform: translateX(0%);
			-webkit-transform-origin: 50% 50%;
			transform-origin: 50% 50%;
		}
		15% {
			-webkit-transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
			transform: translateX(-5px) rotate(6deg); /* Smaller translateX value */
		}
		30% {
			-webkit-transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
			transform: translateX(3px) rotate(-6deg); /* Smaller translateX value */
		}
		45% {
			-webkit-transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
			transform: translateX(-3px) rotate(3.6deg); /* Smaller translateX value */
		}
		60% {
			-webkit-transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
			transform: translateX(2px) rotate(-2.4deg); /* Smaller translateX value */
		}
		75% {
			-webkit-transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
			transform: translateX(-1px) rotate(1.2deg); /* Smaller translateX value */
		}
	}
</style>
